language: android
android:
  components:
    - build-tools-30.0.3
    - android-30
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-21

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-28"

script: ./gradlew :app:build

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - lipcseiadam95@gmail.com
    on_success: always
    on_failure: always